name: dart_pkg_kuznechik
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  ffigen: ^11.0.0

ffigen:
  name: 'Kuznechik'
  language: c
  output:
    bindings: 'kuznechik_bindings.dart'
  headers:
    entry-points:
      - 'kuznechik/kuznechik.h'